snapshot:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/44.yaml

packages:
  - .

extra-deps:
  - ../../../../Lib/inline-js/inline-js
  - ../../../../Lib/inline-js/inline-js-core

# Control whether we use the GHC we find on the path
system-ghc: true

